### ISSUE TITLE
get_history fails with default parameters

### ISSUE THREAD

**Issue by darac** [nwithan8/pytulli#1]
In [tautulli.py](https://github.com/nwithan8/pytulli/blob/master/tautulli/tautulli.py#L725), the function `get_history` is defined as:
```python
    @raw_json
    def get_history(self, grouping: bool = False, include_activity: bool = False, user: str = None, user_id: int = None,
                    rating_key: int = None, parent_rating_key: int = None, grandparent_rating_key: int = None,
                    start_date: datetime = None, section_id: int = None, media_type: str = None,
                    transcode_decision: str = None, guid: str = None, order_column: str = None,
                    order_direction: str = None, start: int = 0, length: int = 25, search: str = None) -> dict:
        grouping = bool_to_int(boolean=grouping)
        include_activity = bool_to_int(boolean=include_activity)
        start_date = datetime_to_string(datetime_object=start_date)
```

And `datetime_to_string` is defined in [utils.py](https://github.com/nwithan8/pytulli/blob/master/tautulli/utils.py#L8) as:
```python
def datetime_to_string(datetime_object: datetime, string_format: str = "%Y-%m-%d"):
    return datetime_object.strftime(fmt=string_format)
```

If `start_date` is not passed to `get_history`, then it takes the default value of `None`, which causes the following exception:
> AttributeError: 'NoneType' object has no attribute 'strftime'

Either `get_history` should define a sensible default (for example `state_date: datetime = datetime.datetime.fromtimestamp(0)`) or `datetime_to_string` should guard against the null value, for example:
```
def datetime_to_string(datetime_object: datetime, string_format: str = "%Y-%m-%d"):
    try:
        return datetime_object.strftime(fmt=string_format)
    except AttributeError:
        return datetime.datetime.fromtimestamp(0).strftime(fmt=string_format)
```

**Comment by nwithan8** [comment]
Thanks for the detailed issue post. I'll fix this as soon as I can, thanks!

**Comment by nwithan8** [comment]
Fixed, will be included in the next release. Thanks again.
