### ISSUE TITLE
Getting validation error when calling `tautulli.get_metadata()`

### ISSUE THREAD

**Issue by adamk33n3r** [nwithan8/pytulli#57]
```
pydantic_core._pydantic_core.ValidationError: 1 validation error for MetadataModel
markers
  Input should be a valid dictionary or instance of MarkerModel [type=model_type, input_value=[{'id': 20176, 'type': 'c...: False, 'final': True}], input_type=list]
    For further information visit https://errors.pydantic.dev/2.6/v/model_type
```

**Comment by adamk33n3r** [comment]
Here is an example for a movie I saw erroring. rating key is `13105` and if I use the raw api it seems to have a markers property
```
[{'id': 20176, 'type': 'credits', 'start_time_offset': 5451785, 'end_time_offset': 5565785, 'first': True, 'final': False}, {'id': 20176, 'type': 'credits', 'start_time_offset': 5635785, 'end_time_offset': 5941984, 'first': False, 'final': True}]
```

**Comment by adamk33n3r** [comment]
Actually, yes I think so. If I change the definition in `Metadata` to `markers: Optional[List[MarkerModel]] = None` then it works.

**Comment by nwithan8** [comment]
> Actually, yes I think so. If I change the definition in `Metadata` to `markers: Optional[List[MarkerModel]] = None` then it works.

Thanks for debugging this, sounds like I missed an alias import, I'll fix it immediately!
